server:
  port: 18380
  servlet:
    context-path: /h1-hack-api/v1.0
  forward-headers-strategy: framework
spring:
  application:
    name: h1-hack-api
  config:
    import: optional:file:.env[.properties]
  servlet:
    multipart:
      max-request-size: 1000MB
      max-file-size: 1000MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  data:
    redis:
      port: 6379
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}